### ISSUE TITLE
Device or resource busy: '/tmp/indexify'

### ISSUE THREAD

**Issue by sadath-12** [tensorlakeai/indexify#1263]
This error occurs when running executor with a custom `executor_cache` such as `/tmp/indexify`

Because the existing `executor_cache` path writes to root dir of the host and sometimes we would not need to run containers in a root mode . 

We wanted to be able to run the executor container with `non-root` with `emptydir` mounts on a custom file path

Here is an example to reproduce the issue 

use this helm chart https://github.com/tensorlakeai/indexify/tree/main/operations/k8s/helm

except that for executor use

```yaml
{{- range .Values.executors }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .name | replace "-" "" }}
  labels:
    {{- include "labels" (dict "name" .name "component" "executors" "global" $) | nindent 4 }}
spec:
  ports:
    - port: 9501
  selector:
    {{- include "labels" (dict "name" .name "component" "executors" "global" $) | nindent 4 }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .name | replace "-" "" }}
  labels:
    {{- include "labels" (dict "name" .name "component" "executors" "global" $) | nindent 4 }}
spec:
  replicas: {{ default .replicas 1 }}
  selector:
    matchLabels:
      {{- include "labels" (dict "name" .name "component" "executors" "global" $) | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "labels" (dict "name" .name "component" "executors" "global" $) | nindent 8 }}
    spec:
      {{- if .nodeSelector }}
      nodeSelector:
        {{- toYaml .nodeSelector | nindent 8 }}
      {{- end }}
      containers:
        - name: executor
          imagePullPolicy: IfNotPresent
          image: {{ .image }}
          resources:
            limits:
              ephemeral-storage: 128Gi
              cpu: 4
              memory: 20Gi
            requests:
              ephemeral-storage: 64Gi
              cpu: 2
              memory: 6Gi
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false    
          command:
            - indexify-cli
            - executor
            - --server-addr
            - indexify-server:8900
            - --executor-cache 
            - /tmp/indexify
          volumeMounts:
            - name: executor-cache
              mountPath: /tmp/indexify
      volumes:
        - name: executor-cache
          emptyDir: {}     
      securityContext:
        seccompProfile:
          type: RuntimeDefault 
{{- end }}
```
