### ISSUE TITLE
Peer connection timeout 

### ISSUE THREAD

**Issue by sadath-12** [tensorlakeai/indexify#972]
Executors timeout the connection when executing long running workflow . 
Given this happens only while using https

**Comment by ockhamlabs** [comment]
@sadath-12 Can you confirm https is needed because of use of ingress of adding auth to the APIs

**Comment by sadath-12** [comment]
@ockhamlabs that's right . 

I tried to increase timeout via ingress configuration by setting up fields 

```yaml
nginx.ingress.kubernetes.io/proxy-read-timeout: "1800"
nginx.ingress.kubernetes.io/proxy-send-timeout: "1800"
nginx.ingress.kubernetes.io/proxy-connect-timeout: "180"
nginx.ingress.kubernetes.io/proxy-buffering: "off"
```
I was able to process the file in https server , wondering if this is the right approach for the problem
